# Generated by Django 4.2.3 on 2023-08-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockhistory',
            name='expire',
            field=models.DateField(blank=True, null=True),
        ),
    ]
