# Generated by Django 4.2.3 on 2023-07-27 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6313da42-4b95-4d5c-81d9-3a42a8daa6ab'), editable=False, primary_key=True, serialize=False),
        ),
    ]
