# Generated by Django 4.2.3 on 2023-07-27 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b7a235b-10e1-4f0b-8d1d-b6df82dc472b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
