# Generated by Django 4.2.3 on 2023-07-31 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Otp',
        ),
    ]
