# Generated by Django 4.2.3 on 2023-08-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0002_aircraft_image_aircraftitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraftitem',
            name='aircraft',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
