# Generated by Django 4.2.3 on 2023-08-01 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0003_alter_aircraftitem_aircraft'),
    ]

    operations = [
    ]
