# Generated by Django 4.2.3 on 2023-07-27 19:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('08093f49-ac37-4fd3-8e89-05833672fac9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
