# Generated by Django 4.2.3 on 2023-07-27 19:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0e16d158-cb1e-4e77-844b-75e13878e06b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
