# Generated by Django 4.2.3 on 2023-08-06 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_permitted_aircrafts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aircrafts',
        ),
    ]
