# Generated by Django 4.2.3 on 2023-08-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircraft', '0004_auto_20230802_0103'),
        ('profiles', '0003_profile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aircraft_permissions',
            field=models.ManyToManyField(blank=True, null=True, to='aircraft.aircraft'),
        ),
    ]
