# Generated by Django 4.2.3 on 2023-08-05 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='aircraft_permissions',
            new_name='aircrafts',
        ),
    ]
