# Generated by Django 4.2.3 on 2023-08-05 18:54

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_rename_aircraft_permissions_profile_aircrafts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='aircrafts',
        ),
        migrations.AddField(
            model_name='profile',
            name='aircrafts',
            field=django_mysql.models.ListTextField(models.CharField(max_length=300), blank=True, null=True, size=None),
        ),
    ]
