# Generated by Django 4.2.3 on 2023-08-05 18:55

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_profile_aircrafts_profile_aircrafts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aircrafts',
            field=django_mysql.models.ListTextField(models.CharField(max_length=300), blank=True, default=[], null=True, size=None),
        ),
    ]
