# Generated by Django 4.2.3 on 2023-08-15 12:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_desk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdesk',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
