# Generated by Django 4.2.3 on 2023-08-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='demand_schedule',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
