# Generated by Django 4.2.3 on 2023-08-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ac_stock', '0003_stockrecord_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecord',
            name='latest_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
